Task Lvjavj40
ViktoriyaRyazhska/myosbb pull request #38
Opened 2016-11-25 20:01 UTC by Kvolotc

2016-11-25 21:15 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/Region.java
> +	private Collection<City> citie;
rename to "cities"

2016-11-25 21:16 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/Region.java
> +
Delete emply lines

2016-11-25 21:16 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/Street.java
> +
Delete one blank line - should be only one line between code blocks

2016-11-25 21:17 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/Street.java
> +	}
Please make horizontal formatting of code (move left)

2016-11-25 21:19 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/User.java
> +	public Street getStreet() {
Make horizontal formatting (move left)

2016-11-25 21:19 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/dto/UserDTO.java
> +	public void setApartment(ApartmentDTO apartment) {
MAke horizontal formatting (move left)

2016-11-25 21:20 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/dto/UserDTO.java
> +	public void setApartment(ApartmentDTO apartment) {
Horizontal formatting

2016-11-25 21:21 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/dto/UserRegistrationDTO.java
> +	}
Horizontal formatting

2016-11-25 21:22 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Delete empty lines!!!

2016-11-25 21:23 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Delete

2016-11-25 21:23 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Two extra emply lines! Delete

2016-11-25 21:23 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Delete empty line

2016-11-25 21:23 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Delete two empty lines

2016-11-25 21:24 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Delete empty line

2016-11-25 21:24 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +
Delete empty line

2016-11-25 21:24 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.html
> +                                    <label>РќР°Р·РІР°</label>
WHF?!? 
Use UTF-8 encoding please

2016-11-25 21:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.html
> +                                    <label>РћРїРёСЃР°РЅРЅСЏ</label>
UTF-8 please

2016-11-25 21:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.html
> +                                    <label>РђРґСЂРµСЃ</label>
UTF-8 please

2016-11-25 21:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.html
> +                                    <label>Р Р°Р№РѕРЅ</label>
UTF-8 please

2016-11-25 21:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.html
> +                                    <label>РџРѕСЃРёР»Р°РЅРЅСЏ РЅР° С„РѕС‚Рѕ РґРѕРјСѓ</label>
UTF-8 please

2016-11-25 21:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/shared/models/city.ts
> +}
add new line at the end of file

2016-11-25 21:26 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/shared/models/region.ts
> +}
add new line

2016-11-25 21:26 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/shared/models/street.ts
> +}
add new line

2016-11-25 21:26 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/shared/models/user_registration.ts
>  }
add new line

2016-11-25 21:27 UTC, KostyantynPanchenko requested changes
Please make appropriate changes

2016-11-26 07:52 UTC, ViktoriyaRyazhska commented on persistence/src/main/java/com/softserve/osbb/model/Street.java
> +
**users**
because Collection

2016-11-26 07:56 UTC, ViktoriyaRyazhska commented on web/src/main/resources/public/src/shared/models/street.ts
> +}
variable **cityId** is type City or number?

2016-11-26 07:58 UTC, ViktoriyaRyazhska commented on web/src/main/resources/public/src/shared/models/city.ts
> +}
Which type of regionId: Region or number?

2016-11-26 08:55 UTC, closed without merging