Added SenderMail and added captcha
ViktoriyaRyazhska/myosbb pull request #71
Opened 2016-12-15 23:27 UTC by Kvolotc

2016-12-16 07:56 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/User.java
> +    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
Why eager?

2016-12-16 07:58 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/RegistrationService.java
> +	StringBuilder getPassword();
Not good.

Password should be of type String. If you are constructing password with StringBuilder - just call toString at the end.

2016-12-16 08:11 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +	private StringBuilder password;
Password should be String.

2016-12-16 08:14 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +	public StringBuilder getPassword() {
Should be String

2016-12-16 08:15 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/MailController.java
>          try {
Refactor try-catch to single return statement

2016-12-16 08:16 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/MailController.java
>              logger.error("cannot send message to" + mail.getTo());
Why so much logging?

2016-12-16 08:17 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/RegistrationController.java
> +        	registeredUser.setPassword(registrationService.getPassword().toString());
Refactor password to String

2016-12-16 08:19 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        'Чоловік',
Wrong. Should be an entity and retrieved from DB.
Internationalization also should work

2016-12-16 08:20 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.text = 'Добрий день '+user.firstName+' '+user.lastName+
i18n

2016-12-16 08:20 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.subject = 'Активація';
i18n

2016-12-16 08:20 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.text = 'Добрий день '+user.firstName+' '+user.lastName+
i18n

2016-12-16 08:21 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.subject = 'Деактивація';
i18n

2016-12-16 08:21 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.text = 'Добрий день '+user.firstName+' '+user.lastName+
i18n

2016-12-16 08:21 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.subject = 'Реєстрація Головою Осбб';
i18n

2016-12-16 08:21 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.text = 'Добрий день '+user.firstName+' '+user.lastName+
i18n

2016-12-16 08:21 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/admin/components/users/users.component.ts
> +        this.mail.subject = 'Видалення';
i18n

2016-12-16 08:22 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +        this.avtoGeneratePassword();
avto => auto

2016-12-16 08:23 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +    	if(this.captchaUser == null || this.captchaUser == '' ) {
add space after if

2016-12-16 08:23 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +            this._toasterService.pop('error',' Ви не заповнили капчу');
i18n

2016-12-16 08:24 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +            this._toasterService.pop('error',' Ви погано заповнили капчу');
i18n

2016-12-16 08:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +                	this.sendEmailToUser();
Can you refactor sentEmailToUser and sendEmailToGolova to single method sendTo(<User || String> to)?

2016-12-16 08:30 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +        this.mail.subject = 'Регістрація';
Реєстрація

2016-12-16 08:30 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +    sendEmailToUser() {
refactor to single method sendTo(params)

2016-12-16 08:33 UTC, KostyantynPanchenko requested changes
Please make changes / provide feedback

2016-12-16 21:46 UTC, Kvolotc commented on persistence/src/main/java/com/softserve/osbb/model/User.java
> +    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
it was that befor me . for @ManyToOne it is default

2016-12-19 15:01 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +	private Random  random = new Random();
Indentation lines 40 -83

2016-12-19 15:02 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +
Add blank lines before annotations

2016-12-19 15:02 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +       return (this.password = password.toString());
This is assignment or checking for equality?

2016-12-19 17:01 UTC, Kvolotc commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +	private Random  random = new Random();
here all right

2016-12-19 17:05 UTC, Kvolotc commented on service/src/main/java/com/softserve/osbb/service/impl/RegistrationServiceImpl.java
> +       return (this.password = password.toString());
for Initialization  password and than return

2016-12-19 17:27 UTC, KostyantynPanchenko approved these changes

2016-12-19 18:03 UTC, aprudyus approved these changes

2016-12-19 18:38 UTC, OlegKykena approved these changes

2016-12-19 19:48 UTC, merged