Address Classificator CRUD functional added
ViktoriyaRyazhska/myosbb pull request #77
Opened 2016-12-28 16:34 UTC by YuriPushchalo

Create, Read, Update, Delete functions for Address Classificator realised.
This functional realized only on BackEnd.
FrontEnd is coming soon.

2016-12-28 17:02 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/repository/OsbbRepository.java
>  }
Add new line plz

2016-12-28 17:04 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
Check indentation

2016-12-28 17:04 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(region == null) {
Add space after if before (

2016-12-28 17:04 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(regionRepository.exists(region.getId())) {
if (

2016-12-28 17:04 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(city == null) {
if (

2016-12-28 17:05 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
Check indentation

2016-12-28 17:08 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(districtRepository.exists(district.getId())) {
Space after if

2016-12-28 17:10 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/AddressController.java
> +    @ResponseStatus(HttpStatus.OK)
Why every method return HttpStatus.OK?
I don't see exception handler methods or other mechanism to handle negative situation

2016-12-28 17:10 UTC, KostyantynPanchenko requested changes
Please make changes or provide feedback

2016-12-28 18:24 UTC, YuriPushchalo commented on persistence/src/main/java/com/softserve/osbb/repository/OsbbRepository.java
>  }
+

2016-12-28 20:17 UTC, YuriPushchalo commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
Done

2016-12-28 20:18 UTC, YuriPushchalo commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(region == null) {
Done

2016-12-28 20:18 UTC, YuriPushchalo commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(regionRepository.exists(region.getId())) {
Done

2016-12-28 20:19 UTC, YuriPushchalo commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(city == null) {
Done

2016-12-28 20:19 UTC, YuriPushchalo commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
Done

2016-12-28 20:20 UTC, YuriPushchalo commented on service/src/main/java/com/softserve/osbb/service/impl/AddressServiceImpl.java
> +        if(districtRepository.exists(district.getId())) {
Done

2016-12-28 20:50 UTC, YuriPushchalo commented on web/src/main/java/com/softserve/osbb/controller/AddressController.java
> +    @ResponseStatus(HttpStatus.OK)
ErrorHandler added

2016-12-29 05:38 UTC, KostyantynPanchenko approved these changes

2016-12-29 09:47 UTC, aprudyus approved these changes

2016-12-29 12:00 UTC, thrytsko-amplify approved these changes

2016-12-29 12:44 UTC, merged