Test
ViktoriyaRyazhska/myosbb pull request #78
Opened 2016-12-28 16:39 UTC by Kvolotc

2016-12-28 17:13 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/House.java
> +	@Column(name = "number_house")
Use either @Basic or @Column annotation as ther have almost the same effect

2016-12-28 17:15 UTC, KostyantynPanchenko commented on persistence/src/main/java/com/softserve/osbb/model/User.java
> +		return house;
Fix indentation

2016-12-28 17:19 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/HouseServiceImpl.java
> +
Remove empty line

2016-12-28 17:19 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/HouseServiceImpl.java
> +
Remove empty line

2016-12-28 17:19 UTC, KostyantynPanchenko commented on service/src/main/java/com/softserve/osbb/service/impl/UserServiceImpl.java
> +
Remove empty line

2016-12-28 17:19 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/HouseController.java
> +    		 return new ResponseEntity<>(null,HttpStatus.NOT_FOUND);
Fix indentation

2016-12-28 17:19 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/HouseController.java
> +    		  return new ResponseEntity<>(null,HttpStatus.NOT_FOUND);
Fix indentation

2016-12-28 17:20 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/controller/UserController.java
> +    		 return new ResponseEntity<>(null,HttpStatus.NOT_FOUND);
Fix indentation

2016-12-28 17:21 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/dto/HouseDTO.java
> +
Remove blank ilnes and fix indentation

2016-12-28 17:21 UTC, KostyantynPanchenko commented on web/src/main/java/com/softserve/osbb/dto/HouseDTO.java
> +        public Street getStreet() {
Lines 135 -157 --> fix indentation, remove blank lines

2016-12-28 17:24 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/app/registration/registration_user/registration.component.ts
> +                console.log(value);
delete ALL console.log() -> they are not needed in production

2016-12-28 17:25 UTC, KostyantynPanchenko commented on web/src/main/resources/public/src/shared/services/creatorOsbb.service.ts
> +}
add new line

2016-12-28 17:26 UTC, KostyantynPanchenko requested changes
Please provide:
- description of your pull request
- requested changes or feedback/comments

2016-12-28 20:14 UTC, Kvolotc commented on persistence/src/main/java/com/softserve/osbb/model/House.java
> +	@Column(name = "number_house")
i know)

2016-12-29 13:14 UTC, KostyantynPanchenko approved these changes

2016-12-29 17:15 UTC, merged